[project]
name = "Agents"
version = "0.1.0"
description = "Agent Suite"
authors = ["Kaushal Kumar Subramani <kaushalkmrgr8@gmail.com>"]
requires-python = "==3.12.0"
dependencies = [
    "asyncio",
    "datetime",
    "fastapi",
    "google",
    "google-cloud-secret-manager",
    "langchain",
    "langchain-google-genai",
    "langchain_core",
    "langgraph",
    "msgraph-core",
    "pandas",
    "pydantic",
    "pytest",
    "python-dotenv",
    "redis",
    "requests",
    "scikit-learn",
    "tenacity",
    "tqdm",
    "typing",
    "uuid",
    "uvicorn",
]